# Generated by Django 5.2.6 on 2025-09-27 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaksmap', '0003_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='breach',
            name='leaksmap_br_email_bd2820_idx',
        ),
        migrations.RemoveField(
            model_name='breach',
            name='email',
        ),
        migrations.RemoveField(
            model_name='report',
            name='email',
        ),
        migrations.AddField(
            model_name='breach',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='breach',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processed', 'Processed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='breach',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breaches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='breach',
            index=models.Index(fields=['user'], name='leaksmap_br_user_id_173a58_idx'),
        ),
    ]
